# Generated by Django 6.0.2 on 2026-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Registration & Hacking Open'), ('judging', 'Judging in Progress'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
