# Generated by Django 6.0.2 on 2026-04-08 11:17

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    ParticipantProfile = apps.get_model('core', 'ParticipantProfile')
    OrganizerProfile = apps.get_model('core', 'OrganizerProfile')
    JudgeProfile = apps.get_model('core', 'JudgeProfile')

    for user in User.objects.all():
        if user.role == 'participant':
            ParticipantProfile.objects.get_or_create(user=user)
        elif user.role == 'organizer':
            OrganizerProfile.objects.get_or_create(user=user)
        elif user.role == 'judge':
            JudgeProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_judgeprofile_organizerprofile_participantprofile'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
